language: cpp
script:
        - cmake .
        - make
        - make test
sudo: false
addons:
apt:
        sources:
                - ubuntu-toolchain-r-test
        packages:
                - cmake
                - gcc
                - libboost-all-dev
notifications:
        email:
                recipients:
                        - reo7sp@reo7sp.ru
                on_success: change
                on_failure: always
