language: cpp
script:
        - cmake .
        - make
        - make test
before_script:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -qq
        - sudo apt-get install -qq libboost-all-dev gcc-4.9 g++-4.9
        - export CXX="g++-4.9" CC="gcc-4.9"
